### ISSUE TITLE
Required smartos-live version

### ISSUE THREAD

**Issue by drscream** [joyent/imagetools#4]
I tried to use **imagetools** with the `master`-branch of [smartos-live](https://github.com/joyent/smartos-live) but it started to fail at `create-seed` by trying to copy the `overlay/generic/etc` [data](https://github.com/joyent/imagetools/blob/master/create-seed#L49). I assume that **imagetools** requires a specific (older) version of smartos-live to work correctly?

#### Output

```
+ rsync -av /zones/smartos-src/smartos-live/overlay/generic/etc/ /zones/seed-20210718/root/etc/
sending incremental file list
rsync: change_dir "/zones/smartos-src/smartos-live/overlay/generic/etc" failed: No such file or directory (2)

sent 20 bytes  received 12 bytes  64.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.2]
```

Any support is welcome.

**Comment by jperkin** [comment]
This is with a built smartos-live yeh?  It's possible things have changed since then, to be honest all my images are still based on the 20141030u1 image:

https://us-east.manta.joyent.com/pkgsrc/public/images/seed-20141030u1.json
https://us-east.manta.joyent.com/pkgsrc/public/images/seed-20141030u1.zfs.gz

even the newer builds which are on a 201612 platform.

**Comment by drscream** [comment]
Thanks for that information. I assume that will help me to work with the **imagetools**.

**Comment by drscream** [comment]
Additional to that do you might provide the source of `zstreamdeholer`?

**Comment by jperkin** [comment]
Ah, I don't think I ever had it, @arekinath might?  I can certainly ship you a binary if you're ok to trust it.

**Comment by drscream** [comment]
That would be nice, the current version in the repo isn’t working on the latest smartos platform image. Failing with an segmentation fault.

**Comment by jperkin** [comment]
Ah right, I forgot it was already shipped in the repository.  You might be able to get away without running it, hopefully the bugs it was working around have been fixed since...

**Comment by jasonbking** [comment]
The source might be attached to the JIRA ticket with the original issue...

**Comment by jperkin** [comment]
I found the source but it's in a secret gist belonging to @arekinath so I don't really have the authority to post it, sorry.  Hopefully Alex can chime in and make it public or send you the link privately.

**Comment by drscream** [comment]
Thanks again! I assume (and hope) it's no longer required, but anyway might be interested if it shared at some point in time. :-)
